from plotext._system import platform
import ctypes as c
import sys, os

script_folder = os.path.dirname(os.path.realpath(__file__))
kernel_file_name = 'kernel.dll' if platform == 'windows' else 'kernel.so'
kernel_file_path = os.path.join(script_folder, 'cpp', kernel_file_name)
kernel = c.CDLL(kernel_file_path)

class Clink:
    def add(self, *names):
        name = '_'.join(names)
        cfunction = getattr(kernel, name)
        setattr(self, name, cfunction)
        setattr(self, 'last', cfunction)
        return self

    def input(self, *args):
        setattr(self.last, 'argtypes', list(args))
        return self

    def output(self, output):
        setattr(self.last, 'restype', output)
        return self

clink = Clink()

void = c.c_void_p
size = c.c_size_t
integer = c.c_int
float = c.c_float
float_pointer = c.POINTER(c.c_float)
bool = c.c_bool
wstring = c.c_wchar_p
string = c.c_char_p
wchar = c.c_wchar
cstring = c.POINTER(c.c_wchar)

clink.add('rescale').input(float, float, float, size, float).output(float)
clink.add('wstring', 'delete').input(wstring).output(void)

clink.add('pixel', 'new').input().output(void)
clink.add('pixel', 'delete').input(void).output(void)
clink.add('pixel', 'set', 'fullground', 'integer').input(void, size).output(void)
clink.add('pixel', 'set', 'fullground', 'rgb').input(void, size, size, size).output(void)
clink.add('pixel', 'set', 'fullground', 'code').input(void, string).output(void)
clink.add('pixel', 'set', 'background', 'integer').input(void, size).output(void)
clink.add('pixel', 'set', 'background', 'rgb').input(void, size, size, size).output(void)
clink.add('pixel', 'set', 'background', 'code').input(void, string).output(void)
clink.add('pixel', 'set', 'style', 'code').input(void, string).output(void)
clink.add('pixel', 'get', 'wstring').input(void).output(cstring)
clink.add('pixel', 'log').input(void).output(void)
clink.add('pixel', 'copy').input(void).output(void)
clink.add('pixel', 'no', 'background').input(void).output(bool)
clink.add('pixel', 'copy', 'background').input(void, void).output(void)
clink.add('pixel', 'copy', 'pixel').input(void, void).output(void)
clink.add('pixel', 'fix', 'background').input(void, void).output(void)
clink.add('pixel', 'fix').input(void, void).output(void)

clink.add('colorize', 'new').input(wstring, void).output(void)
clink.add('colorize', 'delete').input(void).output(void)
clink.add('colorize', 'get', 'length').input(void).output(size)
clink.add('colorize', 'get', 'wstring').input(void, bool).output(cstring)
clink.add('colorize', 'get', 'matrix').input(void).output(void)
clink.add('colorize', 'get', 'pixel').input(void).output(void)
clink.add('colorize', 'set', 'pixel').input(void).output(void)
clink.add('colorize', 'part').input(void, size, size).output(void)
clink.add('colorize', 'print').input(void, bool).output(void)
clink.add('colorize', 'copy').input(void).output(void)
clink.add('colorize', 'copy', 'from').input(void, void).output(void)
clink.add('colorize', 'equals').input(void, void).output(bool)
clink.add('colorize', 'no', 'background').input(void).output(bool)
clink.add('colorize', 'copy', 'background').input(void, void).output(void)
clink.add('colorize', 'fix', 'background').input(void, void).output(void)

clink.add('matrix', 'new').input(size, size).output(void)
clink.add('matrix', 'clear').input(void).output(void)
clink.add('matrix', 'delete').input().output(void)
clink.add('matrix', 'get', 'width').input(void).output(size)
clink.add('matrix', 'get', 'height').input(void).output(size)
clink.add('matrix', 'vstack').input(void, void, bool).output(void)
clink.add('matrix', 'hstack').input(void, void, bool).output(void)
clink.add('matrix', 'get', 'wstring').input(void, bool).output(cstring)
clink.add('matrix', 'part').input(void, size, size, size, size).output(void)
clink.add('matrix', 'is', 'empty').input(void, size, size, size, size).output(bool)
clink.add('matrix', 'print').input(void, bool).output(void)
clink.add('matrix', 'copy').input(void).output(void)
clink.add('matrix', 'insert', 'matrix').input(void, size, size, void).output(void)
clink.add('matrix', 'insert', 'matrix', 'aligned').input(void, size, size, void, integer, integer).output(void)
clink.add('matrix', 'insert', 'colorized', 'aligned').input(void, size, size, void, integer, bool).output(bool)
clink.add('matrix', 'insert', 'colorized', 'dynamically').input(void, size, size, void).output(integer)
clink.add('matrix', 'insert', 'wstring').input(void, size, size, wstring).output(void)
clink.add('matrix', 'set', 'wcharacter').input(void, size, size, wchar).output(void)
clink.add('matrix', 'set', 'pixel').input(void, size, size, void).output(void)
clink.add('matrix', 'insert', 'points').input(void, void).output(void)
clink.add('matrix', 'fill', 'pixel').input(void, void).output(void)
clink.add('fast', 'print').input().output(void)

clink.add('marker', 'new', 'normal').input(wchar, void).output(void)
clink.add('marker', 'new', 'type').input(size, void).output(void)
clink.add('marker', 'delete').input().output(void)
clink.add('marker', 'copy').input(void).output(void)
clink.add('marker', 'get', 'wstring').input(void).output(cstring)
clink.add('marker', 'get', 'model').input(void).output(cstring)
clink.add('marker', 'get', 'pixel').input(void).output(void)
clink.add('marker', 'fix').input(void, void).output(void)

clink.add('point', 'filled', 'new').input(float, float, void).output(void)
clink.add('point', 'filled', 'get', 'marker').input(void).output(void)
clink.add('point', 'filled', 'delete').input().output(void)
clink.add('point', 'filled', 'get', 'wstring').input(void, bool).output(cstring)
clink.add('point', 'filled', 'get', 'col').input(void).output(size)
clink.add('point', 'filled', 'get', 'row').input(void).output(size)
clink.add('point', 'filled', 'get', 'x').input(void).output(float)
clink.add('point', 'filled', 'get', 'y').input(void).output(float)
clink.add('point', 'filled', 'get', 'marker').input(void).output(void)
clink.add('point', 'filled', 'get', 'code').input(void).output(size)

clink.add('points', 'new').input(size).output(void)
clink.add('points', 'delete').input(void).output(void)
clink.add('points', 'clear').input(void).output(void)
clink.add('points', 'append', 'point').input(void, void).output(void)
clink.add('points', 'append', 'points').input(void, void).output(void)
clink.add('points', 'get', 'point').input(void, size).output(void)
clink.add('points', 'get', 'length').input(void).output(size)
clink.add('points', 'add', 'offset').input(void, size, size).output(void)
clink.add('points', 'select', 'in', 'matrix').input(void, size, size).output(void)
clink.add('points', 'fix', 'background').input(void, void).output(void)
clink.add('points', 'squash').input(void).output(void)
clink.add('points', 'log').input(void).output(void)
clink.add('points', 'copy').input(void).output(void)
clink.add('points', 'map', 'new').input(size, size).output(void)
clink.add('points', 'map', 'delete').input(void).output(void)
clink.add('points', 'map', 'log').input(void).output(void)
clink.add('points', 'map', 'clear').input(void).output(void)
clink.add('points', 'map', 'get', 'length').input(void).output(size)

clink.add('point', 'new', 'marker').input(float, float, void).output(void)
clink.add('point', 'delete').input(void).output(void)
clink.add('point', 'get', 'x').input(void).output(float)
clink.add('point', 'get', 'y').input(void).output(float)
clink.add('point', 'get', 'wstring').input(void).output(cstring)
clink.add('point', 'log').input(void).output(void)

clink.add('signal', 'new').input(size).output(void)
clink.add('signal', 'delete').input(void).output(void)
clink.add('signal', 'clear').input(void).output(void)
clink.add('signal', 'get', 'xside').input(void).output(bool)
clink.add('signal', 'get', 'yside').input(void).output(bool)
clink.add('signal', 'get', 'label').input(void).output(cstring)
clink.add('signal', 'get', 'marker').input(void).output(void)
clink.add('signal', 'get', 'fill', 'method').input(void).output(bool)
clink.add('signal', 'get', 'line', 'method').input(void).output(bool)
clink.add('signal', 'set', 'xside').input(void, bool).output(void)
clink.add('signal', 'set', 'yside').input(void, bool).output(void)
clink.add('signal', 'set', 'label').input(void, wstring).output(void)
clink.add('signal', 'set', 'marker').input(void, void).output(void)
clink.add('signal', 'set', 'fill', 'method').input(void, bool).output(void)
clink.add('signal', 'set', 'line', 'method').input(void, bool).output(void)
clink.add('signal', 'add', 'point').input(void, void).output(void)
clink.add('signal', 'append').input(void, void).output(void)
clink.add('signal', 'set', 'point').input(void, size, float, float, void).output(void)
clink.add('signal', 'set', 'fill', 'point').input(void, size, float, float, void).output(void)
clink.add('signal', 'get', 'point').input(void, size).output(void)
clink.add('signal', 'get', 'fill', 'point').input(void, size).output(void)
clink.add('signal', 'log', 'x').input(void).output(void)
clink.add('signal', 'log', 'y').input(void).output(void)
clink.add('signal', 'rescale', 'x').input(void, float, float, size, float).output(float)
clink.add('signal', 'rescale', 'y').input(void, float, float, size, float).output(float)
clink.add('signal', 'add', 'offset').input(void, size, size).output(void)
clink.add('signal', 'select', 'in', 'matrix').input(void, size, size).output(void)
clink.add('signal', 'get', 'xmin').input(void, float, float).output(float)
clink.add('signal', 'get', 'xmax').input(void, float, float).output(float)
clink.add('signal', 'get', 'ymin').input(void, float, float).output(float)
clink.add('signal', 'get', 'ymax').input(void, float, float).output(float)
clink.add('signal', 'copy').input(void).output(void)
clink.add('signal', 'assign').input(void, void).output(void)
clink.add('signal', 'fix', 'background').input(void, void).output(void)
clink.add('signal', 'plot').input(void).output(void)
clink.add('signal', 'get', 'wstring').input(void, bool).output(cstring)
clink.add('signal', 'get', 'length').input(void).output(size)
clink.add('signal', 'get', 'filled', 'points').input(void).output(void)