// Point: a 2D position (inherits Position) carrying an OWNED Marker (deep-copied via Marker::copy on construction/copy). Owning lifetime keeps Point usable independently of any Python/marker handle being garbage-collected.

class Point : public Position {
private:
    Marker * marker = nullptr;        // owned, destroyed in ~Point, deep-copied in copy paths

public:
    Point() noexcept = default;
    Point(float x, float y, Marker * m = nullptr) noexcept : Position(x, y), marker(m ? m->copy() : nullptr) {}
    ~Point() noexcept { delete marker; }

    Point(const Point & o) noexcept : Position(o), marker(o.marker ? o.marker->copy() : nullptr) {}
    Point(Point && o) noexcept : Position(o), marker(o.marker) { o.marker = nullptr; }
    Point & operator=(const Point & o) noexcept {
        if (this != &o) { delete marker; Position::operator=(o); marker = o.marker ? o.marker->copy() : nullptr; }
        return *this; }
    Point & operator=(Point && o) noexcept {
        if (this != &o) { delete marker; Position::operator=(o); marker = o.marker; o.marker = nullptr; }
        return *this; }

    inline Marker * get_marker() const noexcept { return marker; }
    inline void     set_marker(Marker * m) noexcept { delete marker; marker = m ? m->copy() : nullptr; }
    inline bool     has_marker() const noexcept { return marker != nullptr; }
    inline uint8_t  get_type()   const noexcept { return marker ? marker->get_type() : marker_none; }     // null-safe, returns marker_none when no marker

    // Sub-cell dot coords inside the marker glyph (fractional part of x/y scaled by marker grid)
    inline unsigned char get_subcell_col() const noexcept { return marker ? static_cast<unsigned char>((get_x() - get_col()) * marker->get_xres()) : 0; }
    inline unsigned char get_subcell_row() const noexcept { return marker ? static_cast<unsigned char>((get_y() - get_row()) * marker->get_yres()) : 0; }

    // ------- line generation -------

    // Sub-column distance from this point to p, measured in marker dots (e.g. Braille has 2 cols/cell).
    inline size_t get_x_distance_to(const Point & p) const noexcept {
        const size_t cols = marker ? marker->get_xres() : 1;
        return static_cast<size_t>(std::abs(static_cast<int>(get_x() * cols) - static_cast<int>(p.get_x() * cols))); }

    // Sub-row distance from this point to p, measured in marker dots.
    inline size_t get_y_distance_to(const Point & p) const noexcept {
        const size_t rows = marker ? marker->get_yres() : 1;
        return static_cast<size_t>(std::abs(static_cast<int>(get_y() * rows) - static_cast<int>(p.get_y() * rows))); }

    // Sub-cell grid dims of this Point's marker (1 when no marker).
    inline size_t get_xres() const noexcept { return marker ? marker->get_xres() : 1; }
    inline size_t get_yres() const noexcept { return marker ? marker->get_yres() : 1; }

    // Number of points to generate sampling a simple (linspace) line from this to p (inclusive of both endpoints).
    inline size_t get_simple_line_size(const Point & p) const noexcept {
        return std::max({get_x_distance_to(p), get_y_distance_to(p), (size_t)1}) + 1; }

    // Upper bound on points generated by get_full_line: every grid-cell crossing plus the two endpoints and the trailing midpoint.
    inline size_t get_full_line_size(const Point & p) const noexcept {
        return get_x_distance_to(p) + get_y_distance_to(p) + 3; }

    // Dispatcher: simple (method=false) vs full (method=true) line sample count.
    inline size_t get_line_size(const Point & p, bool method = false) const noexcept {
        return method ? get_full_line_size(p) : get_simple_line_size(p); }

    // Single point along the line from this to p at parameter t in [0, 1] (0 = this, 1 = p). Inherits this's marker.
    inline Point get_line_point(const Point & p, float t) const noexcept {
        return Point(get_x() + (p.get_x() - get_x()) * t, get_y() + (p.get_y() - get_y()) * t, marker); }

    // Midpoint between this and p, inheriting this's marker.
    inline Point get_middle_point(const Point & p) const noexcept {
        return Point((get_x() + p.get_x()) * 0.5f, (get_y() + p.get_y()) * 0.5f, marker); }

    // True when two Points are "close enough" to be considered overlapping: same marker kind, same (col, row), same sub-cell (dot_col, dot_row). Used by Points::squash to deduplicate. Compares marker TYPE rather than pointer (each Point owns its own deep-copied marker, so pointers always differ).
    inline bool is_close(const Point & p) const noexcept {
        return get_type()    == p.get_type()
            && get_col()     == p.get_col()     && get_row()     == p.get_row()
            && get_subcell_col() == p.get_subcell_col() && get_subcell_row() == p.get_subcell_row(); }

    // Simple line: linspace-sampled points between this and p (inclusive). last=false omits the trailing endpoint (use when chaining segments).
    inline Vector<Point> get_simple_line(const Point & p, bool last = true) const noexcept {
        const size_t n = get_simple_line_size(p);
        Vector<float> ts = linspace<float>(0.0f, 1.0f, n);
        Vector<Point> out(n);
        out.append(*this);
        for (size_t i = 1; i + 1 < n; ++i) out.append(get_line_point(p, ts.at(i)));
        if (last) out.append(p);
        return out; }

    // Full line: walks every sub-cell boundary between this and p, placing a point at each crossing's midpoint. Denser/more uniform coverage than the simple version, fills cells the simple line would skip on shallow slopes. Same walk the old kernel did.
    inline Vector<Point> get_full_line(const Point & p, bool last = true) const noexcept {
        const float cols = static_cast<float>(get_xres());
        const float rows = static_cast<float>(get_yres());

        const float x0 = get_x()   * cols, x1 = p.get_x() * cols;
        const float y0 = get_y()   * rows, y1 = p.get_y() * rows;
        const float dx = x1 - x0,          dy = y1 - y0;

        Vector<Point> out(get_full_line_size(p) + 4);
        out.append(*this);

        if (std::abs(dx) < 1e-6f && std::abs(dy) < 1e-6f) {                     // degenerate point
            if (last) out.append(p);
            return out; }

        const float m  = (std::abs(dx) < 1e-6f) ? 0.0f : dy / dx;
        const float mi = (std::abs(dy) < 1e-6f) ? 0.0f : dx / dy;
        const float delta_x = dx >= 0 ? 1.0f : -1.0f;
        const float delta_y = dy >= 0 ? 1.0f : -1.0f;
        float x_int = dx >= 0 ? std::floor(x0) + 1 : std::ceil(x0) - 1;
        float y_int = dy >= 0 ? std::floor(y0) + 1 : std::ceil(y0) - 1;

        Point previous = *this, next, middle;
        while (true) {
            const bool test_x = std::abs(dx) > 1e-6f && (delta_x * (x_int - x0)) < (delta_x * dx);
            const bool test_y = std::abs(dy) > 1e-6f && (delta_y * (y_int - y0)) < (delta_y * dy);
            if (!(test_x || test_y)) break;

            const float x_line = x0 + mi * (y_int - y0);
            const float y_line = y0 + m  * (x_int - x0);

            if (test_x && test_y && std::abs(std::abs(m) - 1) < 1e-4f) {        // diagonal: x and y advance together
                next = Point(x_int / cols, y_int / rows, marker);
                x_int += delta_x; y_int += delta_y; }
            else if (test_x && (!test_y || delta_x * (x_line - x_int) >= 0)) {  // crossing a vertical grid line
                next = Point(x_int / cols, y_line / rows, marker);
                x_int += delta_x; }
            else {                                                              // crossing a horizontal grid line
                next = Point(x_line / cols, y_int / rows, marker);
                y_int += delta_y; }

            middle = previous.get_middle_point(next);
            out.append(middle);
            previous = next; }

        out.append(previous.get_middle_point(p));
        if (last) out.append(p);
        return out; }

    // Dispatcher: simple (method=false) vs full (method=true) line generation.
    inline Vector<Point> get_line(const Point & p, bool last = true, bool method = false) const noexcept {
        return method ? get_full_line(p, last) : get_simple_line(p, last); }

    // Build the MatrixCharacter contribution this Point produces at (col, row). Forwards to the marker's polymorphic builder (each subclass owns the construction logic for its kind).
    inline MatrixCharacter get_matrix_character() const { return marker ? marker->get_matrix_character(get_subcell_col(), get_subcell_row()) : MatrixCharacter(); }

    // Stamp this Point onto target. Marker-null Points are a trivial no-op (return true). MatrixMarker is the multi-cell special case (is_matrix_marker() flags it, then routes to Matrix::insert(Matrix, col, row, ha, va)); every other marker (Normal/HD/FHD/Braille/Box) takes the single-cell path via Point::get_matrix_character (which forwards subcell coords, that's what makes HD dot-merge work and Box arms accumulate).
    inline bool stamp(Matrix & target, bool check_space = false) const noexcept {
        if (!marker) return true;
        if (marker->is_matrix_marker()) {
            const MatrixMarker * mm = static_cast<const MatrixMarker *>(marker);
            return target.insert(*mm, get_col(), get_row(), mm->get_halignment(), mm->get_valignment(), check_space); }
        return target.insert(get_matrix_character(), get_col(), get_row(), check_space); }

    // Single-line "x <x>, y <y>, marker <marker>"
    inline wstring get_wstring() const {
        wchar_t head[50];
        swprintf(head, 50, L"x %.2f, y %.2f, marker ", get_x(), get_y());
        wstring s(head);
        s += marker ? marker->get_wstring() : wstring(L"none");
        return s; }

    inline string  get_string() const { return wstring_to_string(get_wstring()); }
    inline void    log() const { wcout << L"Point(" << get_wstring() << L")" << endl; }
};


extern "C" {
    Point * point_new_marker(float x, float y, Marker * m) noexcept { return new Point(x, y, m); }
    void    point_delete    (Point * p) noexcept { delete p; }
    float   point_get_x     (Point * p) noexcept { return p->get_x(); }
    float   point_get_y     (Point * p) noexcept { return p->get_y(); }
    void    point_log       (Point * p) noexcept { p->log(); }
    const wchar_t * point_get_wstring(Point * p) noexcept { return wstring_to_cstring(p->get_wstring()); }
    bool    matrix_insert_point(Matrix * m, Point * p, bool check_space) noexcept { return m->insert(*p, check_space); }
}


// Stamp a Point: delegates to Point::stamp, which invokes the marker's polymorphic stamp method. Returns the stamp() bool. Declared inside Matrix's class body in 07_matrix.cpp; defined here because Point must be fully declared first.
inline bool Matrix::insert(const Point & p, bool check_space) noexcept { return p.stamp(*this, check_space); }
