# The explanations shared by many docstrings: the value each parameter takes, and the recurring messages.

from plotext.prettydoc import registry
from plotext._settings.themes import themes as _themes


explanation = registry()

# Simple values
explanation.add("float", "a numeric value")
explanation.add("floats", "a list of numeric values")
explanation.add("int", "an integer")
explanation.add("bool", "a boolean value")
explanation.add("string", "a string")
explanation.add("int_tuple", "a tuple of integer values")
explanation.add("rgb_tuple", "a tuple of three integers, each from 0 to 255, or None")

# Plotext objects
explanation.add("figure", "a plotext figure object")
explanation.add("signal", "a plotext signal object")
explanation.add("marker", "a plotext marker object")
explanation.add("terminal", "a plotext terminal object")
explanation.add("pixel", "a plotext pixel object")
explanation.add("colorize", "a plotext colorize object")
explanation.add("matrix", "a plotext matrix object")
explanation.add("point", "a plotext point object")
explanation.add("ruler", "a plotext ruler selection object")
explanation.add("clear", "a plotext clear object")
explanation.add("date_converter", "a plotext date selection object")
explanation.add("couple", "a two-value tuple or list")
explanation.add("function", "a Python callable, or a list of callables")
explanation.add("function_key", "a string: the function __name__ attribute, or the name set with the function() name parameter, prefixed by the source path when one is set using the source() method")
explanation.add("docs", "a plotext.prettydoc docs manager object")
explanation.add("documentation", "a plotext.prettydoc documentation container object")
explanation.add("registry", "a plotext.prettydoc registry object")
explanation.add("file", "the plotext file toolkit")
explanation.add("prettydoc", "the plotext prettydoc package")
explanation.add("line", "a plotext line object")
explanation.add("matplotlib_figure", "a matplotlib figure object")

# Longer explanations
explanation.add("axis", "the strings x or y, or the integers 0 or 1")
explanation.add("side", "the strings lower or upper for the x axis, left or right for the y axis, or the integers 0 or 1")

explanation.add("axis_multiple", explanation("axis") + "; a list of the two axes, or the word both, is also allowed")
explanation.add("side_multiple", explanation("side") + "; a list of the two sides, or the word both, is also allowed")

explanation.add("xside", "the strings lower or upper, or the integers 0 or 1")
explanation.add("yside", "the strings left or right, or the integers 0 or 1")

explanation.add("label", "a string, a plotext.colorize object, or a plotext.matrix object")
explanation.add("labels", "a list of strings, plotext.colorize objects, or plotext.matrix objects")
explanation.add("bar_labeled", "a boolean value, or a list of texts, one per bar, each " + explanation("label") + "; with grouped or stacked bars, a list of such lists, one per series, as the heights are given")
explanation.add("scale", "the strings linear or log")
explanation.add("alignment", "the strings center or edge")
explanation.add("direction", "the integers 1 or -1")
explanation.add("line_method", "the strings simple or full, or the integers 0 or 1")
explanation.add("line_style", "the strings default, double, heavy or dotted")
explanation.add("axis_style", "the strings default, double, heavy, dotted or rounded")
explanation.add("line_method_scope", "the strings line, fill or both")
explanation.add("orientation", "the strings horizontal or vertical (short h, v), or the integers 0 or 1")
explanation.add("alignment_h", "the strings left, center or right (short l, c, r), or the integers -1, 0 or 1")
explanation.add("alignment_tick", "on the x axis, the strings left, center, right or dynamic (short l, c, r, integers -1, 0, 1 or 2); on the y axis, the strings left, center or right (short l, c, r, integers -1, 0 or 1); on both, the string default, which is the dynamic alignment on the x axis and the alignment against the axis on the y one")
explanation.add("alignment_v", "the strings top, center or bottom (short t, c, b), or the integers -1, 0 or 1")
explanation.add("alignment_text", "the strings left, center or right for horizontal text (short l, c, r), top, center or bottom for vertical text (short t, c, b), or the integers -1, 0 or 1")
explanation.add("size_policy", "the strings minimum or maximum (short min, max), or the integers 0 or 1")
explanation.add("ohlc_dict", "a dict with keys date, open, close, high, low; each holding a sequence of values (date may be strings, timestamps, or datetime objects; the others are numeric)")
explanation.add("matrix_insertable", "a plotext.matrix, plotext.colorize, or raw string")
explanation.add("style", "a style code string, or multiple codes combined into one space-separated string")
explanation.add("date", "dates, once activated on the relevant axis via figure.date().activate(), may be provided as string, timestamp (int or float), or a Python/Pandas datetime object.")
explanation.add("date_par", "a date as string, timestamp (int or float), or a Python/Pandas datetime object")
explanation.add("date_output", "one string among: string, datetime or timestamp")
explanation.add("theme", "one string among: " + ", ".join(_themes))
explanation.add("value", "a numeric value or date; " + explanation("date"))
explanation.add("data_single", "a sequence of numeric values or dates; " + explanation("date"))
explanation.add("data_multiple", "one or two sequences of numeric values or dates; " + explanation("date"))
explanation.add("data_bar", "one, two, or three sequences of numeric values or dates: one sets the bar heights, two set the bar coordinates and heights, three set the bar coordinates, baselines and heights; the heights may also be a list of sequences, one per group. " + explanation("date"))
explanation.add("data_error", "one to four sequences of numeric values; the third and fourth (the errors) may also be single numbers")
explanation.add("data_2d", "a 2D sequence; either numeric values, or (r, g, b) integer triples")
explanation.add("colormap", "the strings gray or viridis")
explanation.add("cell_symbol", "a single character or a named symbol code from plotext.markers(); high resolution codes (hd, fhd, braille) are accepted but not recommended")
explanation.add("marker_par", "a single character, a code from plotext.markers(), a plotext.matrix or plotext.colorize for a multi-cell marker, a plotext.marker() object, or a list of any of these (one per point)")
explanation.add("marker_symbol", "a single character, a code from plotext.markers(), or a plotext.matrix or plotext.colorize for a multi-cell marker")
explanation.add("marker_default", "'hd'")
explanation.add("pixel_par", "a plotext.pixel object, a foreground string or integer, a tuple specifying (foreground, background, style), or an (r, g, b) integer triple used as foreground alone")
explanation.add("color", "a string color code, an integer (from 0 to 255), or a tuple of 3 integers (each from 0 to 255)")

# Recurring messages
explanation.add("colors", "Use plotext.colors() for the available color codes.")
explanation.add("styles", "Use plotext.styles() for the available style codes.")
explanation.add("line_styles", "Use plotext.line_styles() for a preview of the available styles.")
explanation.add("limits", "If not provided, the limit is calculated automatically.")
explanation.add("label_colors", "Its colors are picked automatically: over a filled shape they contrast the fill, over an outlined one they match the outline.")
explanation.add("dates_accepted", "Dates (as string, timestamp, or datetime) are accepted once activated on the axis via figure.date().activate().")
